### ISSUE TITLE
id.gs1.org TLS config is broken

### ISSUE THREAD

**Issue by Synchro** [gs1/DigitalLinkDocs#9]
I noticed that the resolver on `id.gs1.org` has a broken TLS config as soon as I tried to use it; looks like it's missing an intermediate certificate. See [Qualys test results](https://www.ssllabs.com/ssltest/analyze.html?d=id.gs1.org).

![Qualys results](https://user-images.githubusercontent.com/81561/102257043-78932a00-3f0c-11eb-9b5e-03fce86baeb2.png)

I deal with this kind of thing a lot – let me know if you need help with it.

**Comment by nicklansley** [comment]
HI Synchro

Many thanks - yes we did have an intermediate cerificate issue, thankfully solved!
Always happy for advice if this reoccurs.
![image](https://user-images.githubusercontent.com/3082509/105350421-0edcfe80-5be3-11eb-9f0e-291957b71176.png)
